# Generated by Django 5.1.3 on 2024-12-03 10:27

from django.db import migrations, models


def create_test_model(apps, schema_editor):
    TestModel = apps.get_model("core", "TestModel")

    TestModel.objects.create()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial")
    ]

    operations = [
       migrations.RunPython(create_test_model)
    ]
